# Site settings
title: AJ Weeks
description: AJ Weeks - Game Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://ajweeks.com"

# User settings
username: AJ Weeks
user_description: I love to learn new things, and new ways to approach problems
user_title: Game Developer
email: contact@ajweeks.com
twitter_username: liqwidice
github_username:  ajweeks

sass:
  sass-dir: css
  style: compressed

# Google-analytics
google-analytics:
  id: "UA-57413391-2"

highlighter: rouge

exclude: ['package.json', 'src' , 'node_modules']
